CREATE TABLE BRAND (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
	DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCT (
	ID INT AUTO_INCREMENT  PRIMARY KEY,
	DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE PRICE_LIST (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
	DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE PRICE (
	ID INT AUTO_INCREMENT  PRIMARY KEY,
	BRAND_ID INT NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL,
	PRICE_LIST_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	PRIORITY INT NOT NULL,
	PRICE DOUBLE NOT NULL,
	CURRENCY VARCHAR(10) NOT NULL,
	foreign key (BRAND_ID) references BRAND(ID),
	foreign key (PRODUCT_ID) references PRODUCT(ID),
	foreign key (PRICE_LIST_ID) references PRICE_LIST(ID)
);
